### PR TITLE
Updates to TLG page

### PR DESCRIPTION
**Pull request by rossfarrugia**
# Pull Request

- [x] This is a PR into production (main), and I am doing it from develop
- [x] If from develop, I have checked the code is working on the UAT site http://openpharma.s3-website.us-east-2.amazonaws.com/develop/

# Description
TLG page updates to add falcon, link to RTRS and TLG Catalog.

## Metadata

Please reference any related issues here (using `#issuenumber`): #182 #183 #198
People to notify:

### CODE REVIEW

**Comment by rossfarrugia** [comment]
@NNaikp @epijim @cicdguy looks like we still hit that GH API limit even for minor site updates now like this. any ideas?

**Comment by rossfarrugia** [comment]
I like that idea @NNaikp! as i'll never really touch those components in devel anyway. could you add that to this PR please?

**Comment by NNaikp** [comment]
@rossfarrugia The pipeline has been updated and it seems to work. 
Once this is merged we will know if it works in deployment of main as well 😅

While reviewing the changes I got annoyed with the missing _target=blank again, so I have gone rogue and added a fix for this for all external links. It seems to work correctly on the 20ish links I have clicked, but would appreciate if someone else also clicks a few different links 😄

**Comment by rossfarrugia** [comment]
Looks fine to me @NNaikp - i spotted one typo i made and fixed it. please approve if you're happy and then i'll double check all looks ok when merged to main.

**Review by NNaikp — APPROVED** [review]
Updates looks fine 👍

**Pull request merged**
