### PR TITLE
Viz hex people

### PR DESCRIPTION
**Pull request by NNaikp**
# Pull Request

This is a pull request from a feature branch into develop to perform UAT on a published site.

# Description

Landing page of pharmaverse.org has been updated to include a hexwall and a visual network of packages and contributors.

## Metadata

Please reference any related issues here (using `#issuenumber`): 
#212 
People to notify:

### CODE REVIEW

**Comment by NNaikp** [comment]
@epijim / @rossfarrugia in [Development - git/flow](https://github.com/pharmaverse/pharmaverse#development--git-flow) of the README it is mentioned that there is a GH action for deployment of pull requests onto develop. But it doesn't seem like there is any longer?

I have checked this build by just running 'hugo server' locally and looking at the results.

**Comment by rossfarrugia** [comment]
@NNaikp the action only runs when making the commits in `develop` whereas you're in a feature branch. Also there are some merge conflicts. I just merged latest `develop` updates (adding PHUSE logo) to `main` so that `develop` is all clear ready for these big homepage updates.

@epijim can you sanity check these updates first please and merge this into `develop` and then i'll do some extra checks there and merge to `main`?

**Comment by rossfarrugia** [comment]
Also @NNaikp can you resolve the merge conflicts please here?

**Comment by NNaikp** [comment]
@rossfarrugia I have cleaned up the merge conflicts.

Please let me know if there is anything in relation to hugo that should be changes e.g. placement of files.
I have just made it work for now 😆

**Comment by epijim** [comment]
I'll merge it in then if anything pops up we can hotfix on `develop`. 

The only thing I'm not sure about looking at the commits is the pre-rendering of `badge_cran:` in the yamls. I've forgotten how the scripts work, but I thought that was done in the CI builds. 

But as mentioned, we can sort that out later on develop if it is an issue.

**Pull request merged**
