### PR TITLE
Various website clean-ups around contributing and adding roxytractor and council meeting minutes

### PR DESCRIPTION
**Pull request by rossfarrugia**
# Pull Request

- [x] This is a PR into production (main), and I am doing it from develop
- [x] If from develop, I have checked the code is working on the UAT site https://pharmaverse-staging-test.netlify.app/

# Description

Various website clean-ups around contributing and adding roxytractor and council meeting minutes

## Metadata

Please reference any related issues here (using `#issuenumber`): #335 
People to notify: @website-maintainers

### CODE REVIEW

**Comment by rossfarrugia** [comment]
@sankhadeepdutta are you happy for all these changes to go to `main` branch now or is anything still a work in progress? I added some minor commits for some other updates I needed to make to the site.

One thing I'm not sure of (might be only an issue in the UAT site) - we're not consistently seeing the drop down menu LHS options:

Missing here:

image

Available here (see red box):

image

**Comment by sankhadeepdutta** [comment]
@rossfarrugia I'll look into the dropdown menu issue and finalize the changes for merging to the `main` branch 👍🏻 .

**Comment by rossfarrugia** [comment]
@sankhadeepdutta seems like some other parts of the site have been corrupted too, like for example if you scroll to the bottom of the front page we had removed mention of all the WGs and the council now includes Andre (Sanofi) and Damian (Appsilon). it looks like that section has been replaced by an old version of the site. Can you double check please?

image

**Comment by sankhadeepdutta** [comment]
> @sankhadeepdutta seems like some other parts of the site have been corrupted too, like for example if you scroll to the bottom of the front page we had removed mention of all the WGs and the council now includes Andre (Sanofi) and Damian (Appsilon). it looks like that section has been replaced by an old version of the site. Can you double check please?
> 
> image

Hi @rossfarrugia, have the changes in the Council section been made in the `develop` branch? I was unable to find the commit where the council changes were made. Also, the contributor's section of the development and production site is the same. Could you kindly help me by referring to the required commit?

**Comment by rossfarrugia** [comment]
@sankhadeepdutta see below:

- PR to add new council members: https://github.com/pharmaverse/pharmaverse/pull/295
- PR to update WGs to remove all those besides council: https://github.com/pharmaverse/pharmaverse/pull/302

I think what's happened is that `script/add_contributions.R` must not be running when the site is built, as this reads from the `data/people` folder and usually makes the updates to what is shown on the homepage.

**Comment by sankhadeepdutta** [comment]
@rossfarrugia thanks for the PR references 👍🏻. You are right, add_contributions.R is indeed not running. It was disabled by James in this [commit](https://github.com/pharmaverse/pharmaverse/commit/47246b04b966c93cc63b80f06be2cde85287034d). I guess it was disabled due to the AWS S3 references in the script.

**Comment by rossfarrugia** [comment]
> @rossfarrugia thanks for the PR references 👍🏻. You are right, add_contributions.R is indeed not running. It was disabled by James in this [commit](https://github.com/pharmaverse/pharmaverse/commit/47246b04b966c93cc63b80f06be2cde85287034d). I guess it was disabled due to the AWS S3 references in the script.

I see thanks. Would you be able to get it back running with the new site set-up now? It's an important part of the site as it lists the main pharmaverse contacts (our council members) incl their companies.

**Comment by sankhadeepdutta** [comment]
> > @rossfarrugia thanks for the PR references 👍🏻. You are right, add_contributions.R is indeed not running. It was disabled by James in this [commit](https://github.com/pharmaverse/pharmaverse/commit/47246b04b966c93cc63b80f06be2cde85287034d). I guess it was disabled due to the AWS S3 references in the script.
> 
> I see thanks. Would you be able to get it back running with the new site set-up now? It's an important part of the site as it lists the main pharmaverse contacts (our council members) incl their companies.

Sure! I'll make the necessary changes and open a PR soon.

**Pull request merged**
