### PR TITLE
add envsetup to site

### PR DESCRIPTION
**Pull request by rossfarrugia**
# Pull Request

- [x] This is a PR into production (master), and I am doing it from develop
- [ ] If from develop, I have checked the code is working on the UAT site http://openpharma.s3-website.us-east-2.amazonaws.com/develop/

# Description
Add envsetup

## Metadata

Please reference any related issues here (using `#issuenumber`): 
People to notify: @epijim

### CODE REVIEW

**Comment by rossfarrugia** [comment]
@epijim you ever seen that github pages failure error before? feel free to work on this in the `develop` branch directly. i won't be making any other updates for now, so just need this one to add envsetup to the utilities page

**Comment by epijim** [comment]
Couldn't see an issue. Tried the classic turn it off and on again.

https://github.com/pharmaverse/pharmaverse/runs/8253272351?check_suite_focus=true

**Comment by epijim** [comment]
I copy and pasted the values - so could be I copy and pasted something funky. Tried to fix 'l1', and worse case I manually type out the ~5 lines of code to make sure no errant code.

**Comment by rossfarrugia** [comment]
so weird! something odd going on with this PR generally as the Files Changed tab also shows the updates i already merged via https://github.com/pharmaverse/pharmaverse/pull/139/files. if you want me to try creating the yml from scratch let me know as i'm not on Mac - just in case it is some weird icon from that.

**Pull request closed without merging**
